pipeline {
    agent any
    environment {
        GOOGLE_CREDENTIALS = credentials('jenkins-service-gcp')
        PATH = "/home/muhammadtariq/.local/bin:$PATH"
    }
    stages {
        stage('PRODUCTION') {
            steps {
                sh 'env'
                sh 'echo $PATH'
                sh 'prefect --version'
                // sh '''
                // gcloud auth activate-service-account --key-file=$GOOGLE_CREDENTIALS
                // ./orchestration/build_deployments.sh
                // '''
            }
        }
    }
}