pipeline {
    agent any
    environment {
        GOOGLE_CREDENTIALS = credentials('jenkins-service-gcp')
    }
    stages {
        stage('Authenticate GCP') {
            steps {
                sh '''
                gcloud version
                gcloud auth activate-service-account
                terraform --version  
                '''
            }
        }
    }
}