pipeline {
    agent any
    environment {
        GOOGLE_CREDENTIALS = credentials('jenkins-service-gcp')
    }
    stages {
        stage('Setting Up') {
            steps {
                sh '''
                gcloud version
                gcloud auth activate-service-account --key-file=$GOOGLE_CREDENTIALS
                terraform --version  
                '''
            }
        }
    stage('Deploy Infrastructure'){
        steps {
            sh '''
            terraform init
            terraform apply -auto-approve
            '''
            }
        }
    stage('Build And Push Image'){
        steps{
            sh '''
            ./ci/build_and_push_image.sh    
            '''
            }
        }
    }
    stage('Deploy Prefect'){
        steps{
            sh '''
            python orchestration/blocks.py
            '''
            sh '''
            orchestration/build_deployments.sh
            '''
        }
    }
}